### ISSUE TITLE
Cyanide

### ISSUE THREAD

**Issue by al132mc** [al132mc/chem-lib#5]
```
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:428) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181] {}
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75119_b(F)V
	at al132.chemlib.items.DankMolecule.lambda$null$1(DankMolecule.java:49) ~[?:1.14.4-14] {re:classloading}
	at al132.chemlib.items.DankMolecule.activateForPlayer(DankMolecule.java:41) ~[?:1.14.4-14] {re:classloading}
	at al132.chemlib.items.CompoundItem.lambda$onItemUseFinish$2(CompoundItem.java:88) ~[?:1.14.4-14] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_181] {}
	at al132.chemlib.items.CompoundItem.func_77654_b(CompoundItem.java:87) ~[?:1.14.4-14] {re:classloading}
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:196) ~[?:?] {re:classloading,xf:fml:quark:add-spacing-for-stack,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_71036_o(LivingEntity.java:2570) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71036_o(ServerPlayerEntity.java:981) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:2462) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1965) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365) ~[?:?] {re:classloading,pl:accesstransformer:B}
	... 8 more
```

**Comment by al132mc** [comment]
Was fixed in an update at some point, just never closed the issue
