### ISSUE TITLE
World doesn't recognize chemlib-1.18.2-2. as the same as ChemLib 1.18.2-2.0.3

### ISSUE THREAD

**Issue by border999** [al132mc/chem-lib#9]
This causes an issue where the game believes that the datapacks are no longer correct and effectively locks me out of the world unless I revert to the the older version

**Comment by Dark-Arcana** [comment]
Not an issue. ChemLib was rewritten. You can't use latest ChemLib with latest Alchemistry. A new rewrite of Alchemistry is coming out really soon. Then you can update. But the mods are completely rewritten so you won't want to use it with an existing world.

**Comment by border999** [comment]
Caused by: java.lang.ClassNotFoundException: al132.chemlib.chemistry.ElementRegistry
game
at al132.alchemistry.utils.StackUtils.atomicNumToStack(StackUtils.java:20) ~[alchemistry-1.18.2-5.jar%2373!/:1.18.2-5] {re:classloading}
game
at al132.alchemistry.blocks.fission.FissionRecipe.<init>(FissionRecipe.java:25) ~[alchemistry-1.18.2-5.jar%2373!/:1.18.2-5] {re:classloading}
game
at al132.alchemistry.blocks.fission.FissionRecipeSerializer.fromJson(FissionRecipeSerializer.java:27) ~[alchemistry-1.18.2-5.jar%2373!/:1.18.2-5] {re:classloading}
game
at al132.alchemistry.blocks.fission.FissionRecipeSerializer.m_6729_(FissionRecipeSerializer.java:11) ~[alchemistry-1.18.2-5.jar%2373!/:1.18.2-5] {re:classloading}
game
at net.minecraftforge.common.extensions.IForgeRecipeSerializer.fromJson(IForgeRecipeSerializer.java:23) ~[forge-1.18.2-40.1.54-universal.jar%23589!/:?] {re:classloading,re:mixin}
game
at net.minecraft.world.item.crafting.RecipeManager.fromJson(RecipeManager.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
game
at net.minecraft.world.item.crafting.RecipeManager.m_44045_(RecipeManager.java:150) ~[client-1.18.2-20220404.173914-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
game
at dev.latvian.mods.kubejs.recipe.RecipeEventJS.post(RecipeEventJS.java:266) ~[kubejs-forge-1802.5.4-build.508.jar%23344!/:1802.5.4-build.508] {re:mixin,re:classloading,pl:mixin:APP:mixins.hammerlib.json:bs.kubejs.RecipeEventJSMixin,pl:mixin:A}
game
at net.minecraft.world.item.crafting.RecipeManager.handler$bmi000$customRecipesHead(RecipeManager.java:5528) ~[client-1.18.2-20220404.173914-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
game
at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java) ~[client-1.18.2-20220404.173914-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
game
at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[client-1.18.2-20220404.173914-srg.jar%23584!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
game
at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.2-20220404.173914-srg.jar%23584!/:?] {re:mixin,re:classloading}
game
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}

**Comment by border999** [comment]
might be something else entirely

**Comment by Dark-Arcana** [comment]
No, this is not an issue. The publicly available version of Alchemistry was not written to work with the rewritten version of ChemLib.

**Comment by border999** [comment]
thank you, have a nice day

**Comment by Dark-Arcana** [comment]
You too! The new Alchemistry will be out soon, promise. Then you can try it with the new ChemLib and it will work.

**Comment by border999** [comment]
like today? or in an hour?

**Comment by Dark-Arcana** [comment]
wat

Why would you assume that? xD It takes a lot of time to develop mods. I've been working on the rewrite for about 3 months now. Plan to have a release within the next week, alpha. But might be later than that.
